In [10]:
import numpy as np

x = np.array([0,0,0,0,0,0,1,1,1,1])
unique, counts = np.unique(x, return_counts=True)
unique

array([0, 1])

In [20]:
x = np.array([[0,0,0,0,0,0,1,1,1,1],
             [0,0,0,0,0,0,1,1,1,1]])
x[0,:]


array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [22]:
range(2)

range(0, 2)

In [23]:
range(x.shape[0])
for i in range(x.shape[0]):
    print(i)

0
1


In [11]:
counts

array([6, 4])

In [12]:
max(counts)

6

In [8]:
import pandas as pd

x = pd.DataFrame([1,1,1,0,0,0,1,1,1,1])
x

0
0  1
1  1
2  1
3  0
4  0
5  0
6  1
7  1
8  1
9  1

In [9]:
x.value_counts().max()

7