In [10]:
import pandas as pd
import numpy as np
import MarineDNA as md

In [2]:
test_mat = np.random.randint(5, size=(4, 6))
print(test_mat)

p = md.ranRelPct(test_mat)
print(p)

[[3 4 0 0 1 3]
 [2 0 1 3 3 0]
 [0 3 3 3 4 2]
 [1 1 2 1 1 0]]
[[0.30522744 0.46798209 0.04546993 0.2245303  0.07658423 0.38158745]
 [0.22172885 0.19842203 0.46205077 0.35951607 0.31677776 0.27385216]
 [0.05202749 0.50917607 0.15786188 0.42271165 0.17329326 0.08201126]
 [0.23204172 0.17043014 0.23558922 0.6153469  0.73201259 0.29922816]]


In [3]:
lo_mat = np.log(p / (1 - p))
print(lo_mat)

[[-0.82252734 -0.12824714 -3.04416802 -1.23945824 -2.48968837 -0.48281574]
 [-1.25561972 -1.396186   -0.1520894  -0.57746518 -0.76861975 -0.97516524]
 [-2.90255321  0.0367084  -1.67422358 -0.31165162 -1.56246471 -2.41532858]
 [-1.19681825 -1.58258184 -1.17701564  0.46984428  1.00485769 -0.85097598]]


In [4]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca_fit = pca.fit(lo_mat)

print(pca_fit)

PCA(n_components=2)


In [5]:
scores = pca_fit.transform(lo_mat)
print(scores)

[[ 2.27556746 -1.26303927]
 [-1.01390082 -0.18044575]
 [ 0.92671587  1.87797418]
 [-2.18838251 -0.43448916]]


In [6]:
loadings = np.transpose(pca_fit.components_)
print(loadings)

[[-0.05646932 -0.68597936]
 [ 0.38983154  0.21904963]
 [-0.48496409  0.23198718]
 [-0.29964427  0.16473971]
 [-0.71985046 -0.01639403]
 [-0.04100054 -0.63263227]]
