In [1]:
import numpy as np
import random as ran
import pandas as pd
import MarineDNA as md

In [2]:
test_mat = np.random.randint(5, size=(4, 6))
print(test_mat)

[[0 3 3 3 1 4]
 [0 2 1 4 1 3]
 [4 0 0 1 0 4]
 [1 0 3 3 2 4]]


In [3]:
print(md.ranRelPct(test_mat))

[[0.04678072 0.44858847 0.17168463 0.2752584  0.06242719 0.42233488]
 [0.26818762 0.3224755  0.0261883  0.64047999 0.22289739 0.25574034]
 [0.58196077 0.12134776 0.08462004 0.22677765 0.08265076 0.72907142]
 [0.23348055 0.0829413  0.32926339 0.09406018 0.45704189 0.31316286]]


In [4]:
df = pd.DataFrame(test_mat)

In [5]:
print(df)

   0  1  2  3  4  5
0  0  3  3  3  1  4
1  0  2  1  4  1  3
2  4  0  0  1  0  4
3  1  0  3  3  2  4


In [6]:
print(md.ranRelPct_df(df))

AttributeError: module 'MarineDNA' has no attribute 'RanRelPct_df'