In [1]:
import pandas as pd
import MarineDNA as md
import seaborn as sn
import numpy as np

In [2]:
file1 = "../../../Data/Flyer2018_16S_table_counts.tsv"
asvs1 = pd.read_csv(file1, index_col=0, sep="\t").transpose()

# The raw data

In [3]:
asvs1.head()

ASV ID           495c1bd1608a1dad54d3e2824ce899ef  \
CN18Fc12_8_eDNA                               552   
CN18Fc19_5_eDNA                              7415   
CN18Fc21_6_eDNA                              8749   
CN18Fc22_6_eDNA                              8152   
CN18Fc24_6_eDNA                              7124   

ASV ID           a900b6678ce86851fb16bfafb87f3326  \
CN18Fc12_8_eDNA                               210   
CN18Fc19_5_eDNA                              1933   
CN18Fc21_6_eDNA                              2808   
CN18Fc22_6_eDNA                              1967   
CN18Fc24_6_eDNA                              1671   

ASV ID           c8e360969108fa2125a3d56eb4dad24f  \
CN18Fc12_8_eDNA                               145   
CN18Fc19_5_eDNA                              2089   
CN18Fc21_6_eDNA                              2530   
CN18Fc22_6_eDNA                              2086   
CN18Fc24_6_eDNA                              2343   

ASV ID           72143fd9e63fe40c1258948d2f0d79c3  \
CN18Fc12_8_eDNA                               130   
CN18Fc19_5_eDNA                              1830   
CN18Fc21_6_eDNA                              2516   
CN18Fc22_6_eDNA                              2178   
CN18Fc24_6_eDNA                              2256   

ASV ID           7b6b178fad5599c0e9a734e4fb09fd64  \
CN18Fc12_8_eDNA                               156   
CN18Fc19_5_eDNA                              1742   
CN18Fc21_6_eDNA                              1761   
CN18Fc22_6_eDNA                              1855   
CN18Fc24_6_eDNA                              1812   

ASV ID           4bbec3bb723375416616a87d785ac74a  \
CN18Fc12_8_eDNA                                49   
CN18Fc19_5_eDNA                               488   
CN18Fc21_6_eDNA                               787   
CN18Fc22_6_eDNA                               510   
CN18Fc24_6_eDNA                               720   

ASV ID           0c35cfa523aa27921ef8544a16d1cd36  \
CN18Fc12_8_eDNA                                 0   
CN18Fc19_5_eDNA                               234   
CN18Fc21_6_eDNA                               632   
CN18Fc22_6_eDNA                               353   
CN18Fc24_6_eDNA                               308   

ASV ID           7ec69f2c62aad60e060e588ef687bdd0  \
CN18Fc12_8_eDNA                                89   
CN18Fc19_5_eDNA                               595   
CN18Fc21_6_eDNA                              1162   
CN18Fc22_6_eDNA                               750   
CN18Fc24_6_eDNA                               888   

ASV ID           61e9a50f4346bb3a5b16179b8eca71fa  \
CN18Fc12_8_eDNA                               190   
CN18Fc19_5_eDNA                               767   
CN18Fc21_6_eDNA                              1545   
CN18Fc22_6_eDNA                               988   
CN18Fc24_6_eDNA                              1179   

ASV ID           a140195871278e8fcf9447e42bad8786  ...  \
CN18Fc12_8_eDNA                                97  ...   
CN18Fc19_5_eDNA                               918  ...   
CN18Fc21_6_eDNA                              1252  ...   
CN18Fc22_6_eDNA                               904  ...   
CN18Fc24_6_eDNA                               824  ...   

ASV ID           995cc65bcfa53a868c42615004e99ad3  \
CN18Fc12_8_eDNA                                 0   
CN18Fc19_5_eDNA                                 0   
CN18Fc21_6_eDNA                                 0   
CN18Fc22_6_eDNA                                 0   
CN18Fc24_6_eDNA                                 0   

ASV ID           46b90aab075ecd8e4db549da708550d8  \
CN18Fc12_8_eDNA                                 0   
CN18Fc19_5_eDNA                                 0   
CN18Fc21_6_eDNA                                 0   
CN18Fc22_6_eDNA                                 0   
CN18Fc24_6_eDNA                                 0   

ASV ID           c4e1933274329209b7cf24daf18dfe0d  \
CN18Fc12_8_eDNA                                 0   
CN18Fc19_5_eDNA                     

# Extract an example row (samples) of read counts for a handful of columns (ASVs)

In [4]:
ex_row = asvs1.iloc[0,50:56]
ex_row

ASV ID
9cdadd8a7359a3163fb31ad06be74e8c     0
f936cc0095df2ce79b485df5f7fe631a     4
45aae5b06129baf3325f68a675e9c8e2    16
defcb02ec20f29352cb1b1b267f162a4     8
e1453e7b5954ac141ec0b8c91939512d     0
2ed7d51e061664183c05fbbb56c0787e    31
Name: CN18Fc12_8_eDNA, dtype: int64

# Total number of counts for sample

In [5]:
ex_row.sum()

59

# The observed count relative percentages

In [6]:
print(ex_row / ex_row.sum())

ASV ID
9cdadd8a7359a3163fb31ad06be74e8c    0.000000
f936cc0095df2ce79b485df5f7fe631a    0.067797
45aae5b06129baf3325f68a675e9c8e2    0.271186
defcb02ec20f29352cb1b1b267f162a4    0.135593
e1453e7b5954ac141ec0b8c91939512d    0.000000
2ed7d51e061664183c05fbbb56c0787e    0.525424
Name: CN18Fc12_8_eDNA, dtype: float64


# Compute Beta parameters for each count

In [7]:
alpha = ex_row + 1
beta = ex_row.sum() - ex_row + 1
print(alpha)
print()
print(beta)

ASV ID
9cdadd8a7359a3163fb31ad06be74e8c     1
f936cc0095df2ce79b485df5f7fe631a     5
45aae5b06129baf3325f68a675e9c8e2    17
defcb02ec20f29352cb1b1b267f162a4     9
e1453e7b5954ac141ec0b8c91939512d     1
2ed7d51e061664183c05fbbb56c0787e    32
Name: CN18Fc12_8_eDNA, dtype: int64

ASV ID
9cdadd8a7359a3163fb31ad06be74e8c    60
f936cc0095df2ce79b485df5f7fe631a    56
45aae5b06129baf3325f68a675e9c8e2    44
defcb02ec20f29352cb1b1b267f162a4    52
e1453e7b5954ac141ec0b8c91939512d    60
2ed7d51e061664183c05fbbb56c0787e    29
Name: CN18Fc12_8_eDNA, dtype: int64


# A random draw from the Beta distribution for each cell and convert percentage to sum to 1

In [8]:
beta_draw = np.random.beta(alpha, beta)
print(beta_draw)
print(beta_draw.sum())
print()
unit_draw = beta_draw / beta_draw.sum()
print(unit_draw)
print(unit_draw.sum())

[0.01025295 0.13256931 0.34202312 0.13124267 0.02472988 0.61205727]
1.2528751953232349

[0.00818354 0.10581206 0.27299058 0.10475318 0.01973851 0.48852214]
1.0


# Function to draw a random sample from a row

In [9]:
def betaRow(row):
    ran_row = np.random.beta(row + 1, row.sum() - row + 1)
    ran_row = ran_row / ran_row.sum()
    return ran_row

In [10]:
betaRow(ex_row)

array([0.03029297, 0.05280715, 0.17457084, 0.13208423, 0.01889795,
       0.59134686])

# Function to draw a random sample for the full data frame

In [11]:
# Return data frame of a draw of relative percent of occurrence from a beta distribution
# fit to observed occurrence counts
#   df: data frame where rows = samples and columns = ASVs
def ranRelPct(df, asLogOdds = True):
    # function to return a random draw from a beta distribution for a row
    def betaRow(row):
        ran_row = np.random.beta(row + 1, row.sum() - row + 1)
        ran_row = ran_row / ran_row.sum()
        return ran_row
    # apply function to every row to draw sample of relative percent occurrence
    result = df.apply(betaRow, axis = 1, result_type = 'expand')
    # assign row and column names
    result.index = df.index.values
    result.columns = df.columns.values
    # convert to log-odds if requested
    if asLogOdds:
        result = np.log(result / (1 - result))
    return result

In [12]:
ran_sample = ranRelPct(asvs1)
ran_sample.head()

495c1bd1608a1dad54d3e2824ce899ef  \
CN18Fc12_8_eDNA                         -2.450644   
CN18Fc19_5_eDNA                         -1.566279   
CN18Fc21_6_eDNA                         -1.873763   
CN18Fc22_6_eDNA                         -1.677531   
CN18Fc24_6_eDNA                         -1.897783   

                 a900b6678ce86851fb16bfafb87f3326  \
CN18Fc12_8_eDNA                         -3.473040   
CN18Fc19_5_eDNA                         -3.031368   
CN18Fc21_6_eDNA                         -3.112599   
CN18Fc22_6_eDNA                         -3.219684   
CN18Fc24_6_eDNA                         -3.425755   

                 c8e360969108fa2125a3d56eb4dad24f  \
CN18Fc12_8_eDNA                         -3.811117   
CN18Fc19_5_eDNA                         -2.999913   
CN18Fc21_6_eDNA                         -3.234755   
CN18Fc22_6_eDNA                         -3.212618   
CN18Fc24_6_eDNA                         -3.122939   

                 72143fd9e63fe40c1258948d2f0d79c3  \
CN18Fc12_8_eDNA                         -3.869130   
CN18Fc19_5_eDNA                         -3.131192   
CN18Fc21_6_eDNA                         -3.246793   
CN18Fc22_6_eDNA                         -3.147837   
CN18Fc24_6_eDNA                         -3.117828   

                 7b6b178fad5599c0e9a734e4fb09fd64  \
CN18Fc12_8_eDNA                         -3.720959   
CN18Fc19_5_eDNA                         -3.152215   
CN18Fc21_6_eDNA                         -3.551054   
CN18Fc22_6_eDNA                         -3.313944   
CN18Fc24_6_eDNA                         -3.316237   

                 4bbec3bb723375416616a87d785ac74a  \
CN18Fc12_8_eDNA                         -4.806017   
CN18Fc19_5_eDNA                         -4.469255   
CN18Fc21_6_eDNA                         -4.454543   
CN18Fc22_6_eDNA                         -4.610109   
CN18Fc24_6_eDNA                         -4.312930   

                 0c35cfa523aa27921ef8544a16d1cd36  \
CN18Fc12_8_eDNA                         -9.116762   
CN18Fc19_5_eDNA                         -5.117076   
CN18Fc21_6_eDNA                         -4.595539   
CN18Fc22_6_eDNA                         -5.010904   
CN18Fc24_6_eDNA                         -5.185001   

                 7ec69f2c62aad60e060e588ef687bdd0  \
CN18Fc12_8_eDNA                         -4.121835   
CN18Fc19_5_eDNA                         -4.271957   
CN18Fc21_6_eDNA                         -4.033739   
CN18Fc22_6_eDNA                         -4.200386   
CN18Fc24_6_eDNA                         -4.146500   

                 61e9a50f4346bb3a5b16179b8eca71fa  \
CN18Fc12_8_eDNA                         -3.523816   
CN18Fc19_5_eDNA                         -4.065181   
CN18Fc21_6_eDNA                         -3.668874   
CN18Fc22_6_eDNA                         -4.019917   
CN18Fc24_6_eDNA                         -3.805895   

                 a140195871278e8fcf9447e42bad8786  ...  \
CN18Fc12_8_eDNA                         -4.254303  ...   
CN18Fc19_5_eDNA                         -3.873513  ...   
CN18Fc21_6_eDNA                         -3.978673  ...   
CN18Fc22_6_eDNA                         -4.050784  ...   
CN18Fc24_6_eDNA                         -4.191375  ...   

                 995cc65bcfa53a868c42615004e99ad3  \
CN18Fc12_8_eDNA                         -9.338834   
CN18Fc19_5_eDNA                        -12.246497   
CN18Fc21_6_eDNA                        -10.214942   
CN18Fc22_6_eDNA                        -13.015770   
CN18Fc24_6_eDNA                        -12.951000   

                 46b90aab075ecd8e4db549da708550d8  \
CN18Fc12_8_eDNA                         -9.911631   
CN18Fc19_5_eDNA                        -11.476438   
CN18Fc21_6_eDNA                        -13.959934   
CN18Fc22_6_eDNA                        -11.134813   
CN18Fc24_6_eDNA                        -11.747912   

                 c4e1933274329209b7cf24daf18dfe0d  \
CN18Fc12_8_eDNA                         -9.596166   
CN18Fc19_5_eDNA                        -10.681910   
