In [1]:
import numpy as np
import random as ran

In [2]:
def ranRelPct(mat):
    def drawOneSample(x, total):
        a = x + 1
        return ran.betavariate(a, total - a)
    p = [[drawOneSample(count, sum(row)) for count in row] for row in mat]
    return(np.array(p))

In [3]:
test_mat = np.random.randint(5, size=(4, 6))
print(test_mat)

[[0 3 0 1 0 3]
 [0 1 1 2 0 4]
 [2 1 1 3 0 0]
 [2 0 0 2 2 2]]


In [4]:
print(ranRelPct(test_mat))

[[0.06025637 0.64070463 0.01003007 0.45564048 0.10659206 0.56330264]
 [0.06098899 0.24255544 0.53886416 0.31612821 0.05476879 0.35879289]
 [0.66739798 0.22994133 0.39037374 0.51273666 0.02002007 0.00166347]
 [0.5535508  0.13143933 0.00235194 0.28037971 0.38237116 0.32079415]]
