In [7]:
import numpy as np
import random as ran
import pandas as pd
import MarineDNA as md

In [8]:
test_mat = np.random.randint(5, size=(4, 6))
print(test_mat)

[[2 3 1 0 3 2]
 [3 3 2 3 0 2]
 [2 2 0 2 1 3]
 [2 4 0 1 2 1]]


In [10]:
df = pd.read

In [11]:
print(df)

   0  1  2  3  4  5
0  2  3  1  0  3  2
1  3  3  2  3  0  2
2  2  2  0  2  1  3
3  2  4  0  1  2  1


In [12]:
print(md.ranRelPct_df(df))

0    [0.17606920845486124, 0.22843998663266937, 0.3...
1    [0.2764656713110937, 0.2859338648019954, 0.187...
2    [0.1782558253842127, 0.10437064514196853, 0.21...
3    [0.37788324310730786, 0.6617389635253831, 0.09...
dtype: object
